version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - './conf/nginx:/etc/nginx:ro'
      - './webapp/dist:/var/www/html'
      - './certbot/conf:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
    networks:
      bot:
        aliases:
          - nginx
    ports:
      - '80:80'
      - "443:443"
  bot:
    build:
      context: bot
      dockerfile: ../buildfiles/bot.dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot/bot:/app/bot
    depends_on:
      - redis
    networks:
      bot:
        aliases:
          - bot
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./cache:/data
    networks:
      bot:
        aliases:
          - redis
  back:
    build:
      context: back
      dockerfile: ../buildfiles/back.dockerfile
      target: production
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      SECRET_TOKEN: '${SECRET_TOKEN}'
    volumes:
      - ./back/src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      bot:
        aliases:
          - back
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './data/db:/var/lib/pgdata/data'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      TZ: 'Asia/Vladivostok'
    networks:
      bot:
        aliases:
          - db
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - '.conf/nginx:/etc/nginx'
      - './certbot/conf:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos

networks:
  bot:
    driver: bridge
